#!/bin/bash

script/test-source
script/test-build
script/test-unit
script/test-integration
script/test-docs
tests/release/test-release-artifacts.sh
tests/release/test-release-workflow.sh
tests/release/test-package-signature-docs.sh
